/**
 * Type definitions for ProbabilityChart component
 */

import type { TokenProbability } from '../../providers/types';

/**
 * Props for the ProbabilityChart component
 */
export interface ProbabilityChartProps {
  /** Array of token probabilities to display */
  data: TokenProbability[];
  /** Current temperature value for color styling */
  temperature: number;
  /** Whether the chart is in loading state */
  loading?: boolean;
  /** The token that was selected/generated by the model */
  selectedToken?: string | null;
}

/**
 * Internal data point structure for chart rendering
 */
export interface ChartDataPoint {
  /** The token string */
  token: string;
  /** Normalized probability (0-1) */
  probability: number;
  /** Probability scaled to percentage (0-100) for display */
  displayProbability: number;
  /** Raw log probability value */
  logprob: number;
}

/**
 * Props for the CustomTooltip component
 */
export interface CustomTooltipProps {
  /** Whether the tooltip is active/visible */
  active?: boolean;
  /** Payload data from the chart */
  payload?: Array<{ payload: ChartDataPoint }>;
}

/**
 * Props for the CustomXAxisTick component
 */
export interface CustomXAxisTickProps {
  /** X coordinate for positioning */
  x?: number;
  /** Y coordinate for positioning */
  y?: number;
  /** Tick payload containing the value */
  payload?: { value: string };
}

// Re-export types that consumers might need
export type { TokenProbability };
