/**
 * Type definitions for the LLM Provider abstraction layer
 */

/**
 * Represents a single token with its probability information
 */
export interface TokenProbability {
  /** The token string (could be a word, subword, or character) */
  token: string;
  /** Normalized probability (0-1 range) */
  probability: number;
  /** Raw log probability from the API */
  logprob: number;
}

/**
 * Request parameters for getting logprobs
 */
export interface LogprobsRequest {
  /** The prompt text to complete */
  prompt: string;
  /** Model identifier */
  model: string;
  /** Temperature value (0-1) for controlling randomness */
  temperature: number;
  /** Number of top alternatives to return (default: 10) */
  topK?: number;
  /** AbortController signal for request cancellation */
  signal?: AbortSignal;
}

/**
 * Response from a logprobs request
 */
export interface LogprobsResponse {
  /** Array of token probabilities, sorted by probability descending */
  tokens: TokenProbability[];
  /** The model that was used */
  model: string;
  /** Request latency in milliseconds */
  latencyMs: number;
  /** The token that was actually selected/generated by the model */
  selectedToken?: string;
}

/**
 * Configuration for a model
 */
export interface ModelConfig {
  /** Unique identifier for the model */
  id: string;
  /** Human-readable display name */
  name: string;
}

/**
 * LLM Provider interface - all providers must implement this
 */
export interface LLMProvider {
  /** Unique identifier for the provider */
  readonly id: string;
  /** Human-readable display name */
  readonly name: string;
  /** List of available models */
  readonly models: ModelConfig[];

  /** Check if the provider is available */
  isAvailable(): Promise<boolean>;

  /** Get logprobs for the next token after the given prompt */
  getLogprobs(request: LogprobsRequest): Promise<LogprobsResponse>;
}

/**
 * Provider error types for specific error handling
 */
export type ProviderErrorType =
  | 'API_KEY_MISSING'
  | 'RATE_LIMITED'
  | 'NETWORK_ERROR'
  | 'SERVICE_UNAVAILABLE'
  | 'MODEL_NOT_FOUND'
  | 'INVALID_RESPONSE'
  | 'UNKNOWN';

/**
 * Custom error class for provider errors
 */
export class ProviderError extends Error {
  constructor(
    message: string,
    public readonly type: ProviderErrorType,
    public readonly provider: string,
    public readonly retryable: boolean = false,
    public readonly retryAfterMs?: number
  ) {
    super(message);
    this.name = 'ProviderError';
  }
}

/**
 * Provider with availability status
 */
export interface ProviderWithStatus {
  /** The provider instance */
  provider: LLMProvider;
  /** Whether the provider is currently available */
  available: boolean;
  /** Error message if provider is unavailable */
  error?: string;
}
